//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public string Exercise1 { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<bool> Done { get; set; }
        public string Trainer { get; set; }
        public string Client { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Trainer Trainer1 { get; set; }
    }
}
