//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes.Entites
{
    using System;
    using System.Collections.Generic;

    public partial class WorkDay
    {
        public int Id { get; set; }
        public WorkDay()
        {
            this.Appointments = new HashSet<Registration>();
        }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Trainer { get; set; }

        public virtual ICollection<Registration> Appointments { get; set; }

        public virtual Trainer Trainer1 { get; set; }
    }
}
