//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка_на_обучение
    {
        public int Номер_заявки { get; set; }
        public string Тренер { get; set; }
        public string Администратор { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Квалификация { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
